# 부록: 텐서플로우 텐서

## 종류

- `tensorflow.Tensor`

- `tensorflow.Variable`

### `tensorflow.Tensor` 자료형

- 텐서플로우 라이브러리가 제공하는 텐서 자료형

- `np.ndarray`와 매우 유사

- 하지만 항목을 수정할 수 없는 불변 자료형

### `tf.Variable` 자료형

- 모델 훈련에 사용되는 가변 자료형 텐서    

- 가중치와 편향 텐서 등 값이 변하는 값들을 다루는 텐서

- 기타 성질은 `tf.Tensor` 와 동일.

- 다음 장에서 활용법 소개

### 스칼라: 랭크-0 텐서

```python
>>> import tensorflow as tf
>>> import numpy as np

>>> rank_0_tensor = tf.constant(4)
>>> print(rank_0_tensor)
tf.Tensor(4, shape=(), dtype=int32)

>>> rank_0_tensor.shape
TensorShape([])
```

### 벡터: 랭크-1 텐서

```python
>>> rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
>>> print(rank_1_tensor)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)

>>> rank_1_tensor.shape
TensorShape([3])
```

### 행렬: 랭크-2 텐서

```python
>>> rank_2_tensor = tf.constant([[1, 2],
...                             [3, 4],
...                             [5, 6]], dtype=tf.float16)
>>> print(rank_2_tensor)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)

>>> rank_2_tensor.shape
TensorShape([3, 2])
```

### 랭크-3 텐서

```python
>>> rank_3_tensor = tf.constant([
...   [[0, 1, 2, 3, 4],
...    [5, 6, 7, 8, 9]],
...   [[10, 11, 12, 13, 14],
...    [15, 16, 17, 18, 19]],
...   [[20, 21, 22, 23, 24],
...    [25, 26, 27, 28, 29]]
...   ])

>>> print(rank_3_tensor)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)

>>> rank_3_tensor.shape
TensorShape([3, 2, 5])
```

### 랭크-3 텐서 이해 방식

<table>
<tr>
  <th colspan="3">rank_3_tensor의 모양: <code>[3, 2, 5]</code> </th>
</tr>
<tr>
</tr>
<tr>
  <td>    <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/3-axis_numpy.png">   </td>
  <td>    <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/3-axis_front.png">   </td>
  <td>    <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/3-axis_block.png">   </td>
</tr>
</table>

### 넘파이 어레이로의 변환

```python
>>> np.array(rank_2_tensor)
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)
```

또는

```python
>>> rank_2_tensor.numpy()
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)
```

## 텐서 연산

### 항목별 덧셈

```python
>>> a = tf.constant([[1, 2],
...                  [3, 4]])
>>> b = tf.ones([2,2])

>>> tf.add(a, b)
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>
```

또는

```python
>>> a + b
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>
```

### 항목별 곱셈

```python
>>> a = tf.constant([[1, 2],
...                  [3, 4]])
>>> b = tf.ones([2,2])

>>> tf.multiply(a, b)
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>
```

또는

```python
>>> a * b
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>
```

### 행렬 연산

```python
>>> a = tf.constant([[1, 2],
...                  [3, 4]])
>>> b = tf.ones([2,2])

>>> tf.matmul(a, b)
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]])>
```

또는

```python
>>> a @ b
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]])>
```

### 최대 항목 찾기

```python
>>> c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

>>> tf.reduce_max(c)
<tf.Tensor: shape=(), dtype=float32, numpy=10.0>
```

### 최대 항목의 인덱스 확인

```python
>>> c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

>>> tf.math.argmax(c)
<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0], dtype=int64)>
```

### `softmax()` 함수

```python
>>> c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

>>> tf.nn.softmax(c)
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>
```

### 텐서 자동 변환

```python
>>> tf.convert_to_tensor([1,2,3])
<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

>>> tf.reduce_max([1, 2, 3])
<tf.Tensor: shape=(), dtype=int32, numpy=3>

>>> tf.math.argmax([1, 2, 3])
<tf.Tensor: shape=(), dtype=int64, numpy=2>

>>> tf.nn.softmax(np.array([1.0, 12.0, 33.0]))
<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.26641655e-14, 7.58256042e-10, 9.99999999e-01])>
```

## 텐서의 모양, 랭크, 축, 크기

- 넘파이 어레이의 경우와 동일
    - **모양**: 텐서에 사용된 각각의 축에 사용된 항목의 개수로 구성된 벡터
    - **랭크** 또는 **차원**: 텐서에 사용된 축의 개수
        - 스칼라의 랭크는 0,
        - 벡터의 랭크는 1,
        - 행렬의 랭크는 2.
    - **축**: 텐서 구성에 사용된 축
    - **크기**: 텐서에 포함된 항목의 개수


### 랭크-4 텐서 이해

```python
rank_4_tensor = tf.zeros([3, 2, 4, 5])
```

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/shape.png" alt="A tensor shape is like a vector.">     </td>
<td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/4-axis_block.png" alt="A 4-axis tensor">   </td>
  </tr>
</table>


<div align="center"><img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/shape2.png" style="width:300px;"></div>


```python
>>> rank_4_tensor.dtype
tf.float32

>>> rank_4_tensor.ndim
4

>>> rank_4_tensor.shape
TensorShape([3, 2, 4, 5])

>>> rank_4_tensor.shape[0]
3

>>> rank_4_tensor.shape[-1]
5

>>> tf.size(rank_4_tensor)
<tf.Tensor: shape=(), dtype=int32, numpy=120>

>>> tf.rank(rank_4_tensor)
<tf.Tensor: shape=(), dtype=int32, numpy=4>

>>> tf.shape(rank_4_tensor)
<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 4, 5])>
```

## 인덱싱/슬라이싱

- 넘파이 어레이의 경우와 동일

```python
>>> rank_3_tensor[:, :, 4]
<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  9],
       [14, 19],
       [24, 29]])>
```

<table>
<tr>
    <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/index1.png" style="width:350px;">   </td>
      <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/index2.png" style="width:160px;">   </td>
</tr>
</table>

## 모양 변환

### 항목 저장 순서

```python
>>> rank_3_tensor
<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>
```

<div align="center"><img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/index1.png" style="width:350px;"></div>


```python
>>> tf.reshape(rank_3_tensor, [-1])
<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])>
```

### 축의 순서를 고려하는 좋은 모양 변환

- `3x2x5` 텐서 => `(3x2)x5` 텐서

```python
>>> tf.reshape(rank_3_tensor, [3*2, 5])
<tf.Tensor: shape=(6, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])>
```

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-before.png" style="width:350px;">   </td>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-good2.png" style="width:270px;">   </td>
</tr>
</table>


- `3x2x5` 텐서 => `3x(2x5)` 텐서

```python
>>> tf.reshape(rank_3_tensor, [3, -1])
<tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])>
```

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-before.png" style="width:350px;">   </td>
  <td>   <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-good1.png" style="width:450px;">   </td>
</tr>
</table>


### 축의 순서를 고려하지 않는 나쁜 모양 변환

```python
>>> tf.reshape(rank_3_tensor, [2, 3, 5])

>>> tf.reshape(rank_3_tensor, [5, 6])

>>> try:
...   tf.reshape(rank_3_tensor, [7, -1])
... except Exception as e:
...   print(f"{type(e).__name__}: {e}")
```

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-bad.png" alt="You can't reorder axes, use tf.transpose for that">   </td>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-bad4.png" alt="Anything that mixes the slices of data together is probably wrong.">   </td>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-bad2.png" alt="The new shape must fit exactly.">   </td>
</tr>
</table>

## 텐서 항목의 자료형(`dtype`) 변환

```python
>>> the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
>>> the_f64_tensor
<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.2, 3.3, 4.4])>

>>> the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
>>> the_f16_tensor
<tf.Tensor: shape=(3,), dtype=float16, numpy=array([2.2, 3.3, 4.4], dtype=float16)>

>>> the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
>>> the_u8_tensor
<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([2, 3, 4], dtype=uint8)>
```

## 브로드캐스팅

- 넘파이 어레이의 경우와 동일하게 작동

```python
>>> x = tf.constant([1, 2, 3])
>>> y = tf.constant(2)
>>> z = tf.constant([2, 2, 2])

>>> tf.multiply(x, 2)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)

>>> x * y
tf.Tensor([2 4 6], shape=(3,), dtype=int32)

>>> x * z
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
```

```python
>>> x = tf.reshape(x,[3,1])
>>> y = tf.range(1, 5)

>>> x * y
<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])>
```

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/broadcasting.png" style="width:350px;">   </td>
</tr>
</table>


## 다양한 종류의 텐서

### 비정형 텐서

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/ragged.png" style="width:250px;">   </td>
</tr>
</table>

```python
>>> ragged_list = [
...     [0, 1, 2, 3],
...     [4, 5],
...     [6, 7, 8],
...     [9]]

>>> ragged_tensor = tf.ragged.constant(ragged_list)
>>> ragged_tensor
<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>

>>> ragged_tensor.shape
(4, None)
```

### 희소 텐서

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/sparse.png" style="width:250px;">   </td>
</tr>
</table>

```python
>>> sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
...                                        values=[1, 2],
...                                        dense_shape=[3, 4])

>>> sparse_tensor
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
```

### 밀집 텐서 대 희소 텐서

```python
>>> dense_tensor = tf.sparse.to_dense(sparse_tensor)

>>> dense_tensor
<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]])>


>>> tf.sparse.from_dense(dense_tensor)
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
```