# 3. 텐서

## 3.1. 넘파이 어레이와 텐서

- 넘파이 어레이 `numpy.ndarray`
    - 대표적인 **텐서**<font size='2'>tensor</font> 자료형
    - 머신러닝에 사용되는 데이터셋은 일반적으로 텐서로 저장됨

- 텐서플로우
    - `Tensor` 자료형인 `tensorflow.Tensor`
    - 넘파이 어레이와 유사하며 GPU를 활용한 연산 지원

- 케라스 신경망 모델의 입력, 출력값
    - 넘파이 어레이를 기본으로 사용
    - 내부적으로는 `tf.Tensor`로 변환해서 사용

### 3.1.1. 넘파이 어레이의 차원

- 텐서의 표현에 사용된 **축**<font size='2'>axis</font>의 개수

- **랭크**<font size='2'>rank</font>로도 불림

### 0차원(0D) 어레이 (랭크-0 어레이)

- 정수 한 개, 부동소수점 한 개 등 하나의 수를 표현하는 어레이

- **스칼라**<font size='2'>scalar</font>라고도 불림.

```
>>> x0 = np.array(12)
>>> y0 = np.array(1.34)
```

### 1차원(1D) 어레이 (랭크-1 어레이)

- 수로 이루어진 리스트 형식의 어레이. 

- **벡터**<font size='2'>vector</font>로 불리며 한 개의 축을 가짐.

```
>>> x1 = np.array([12, 3, 6, 14, 7])
```

### 2차원(2D) 어레이 (랭크-2 어레이)

- 행과 열 두 개의 축을 가짐. 

- **행렬**<font size='2'>matrix</font>로도 불림.

```
>>> x2 = np.array([[5, 78, 2, 34, 0],
                   [6, 79, 3, 35, 1],
                   [7, 80, 4, 36, 2]])
```

### 3차원(3D) 어레이 (랭크-3 어레이)

- 행, 열, 깊이 세 개의 축 사용.

- 컬러 이미지 등을 표현할 때 사용

```
>>> x3 = np.array([[[5.0, 7.8, 2.1],
                    [6.0, 7.9, 3],
                    [7, 8.0, 4],
                    [34, 0, 3.5],
                    [1, 3.6, 2]],
                              
                   [[5, 7.8, 2],
                    [3.4, 0, 3.5],
                    [6, 7.9, 3],
                    [7, 8.0, 4],
                    [1, 3.6, 2]]])
```

### 4D 어레이 (랭크-4 어레이)

- 컬러 이미지로 구성된 데이터셋 등을 표현할 때 사용됨

### 주의사항: 벡터의 차원

- **벡터의 길이**를 **차원**이라 부르기도 함

- 예제: `np.array([12, 3, 6, 14, 7])`는 5차원 벡터

### 3.1.2. 넘파이 어레이 주요 속성

### `ndim` 속성: 텐서의 차원 저장

```python
>>> print(x0.ndim, x1.ndim, x2.ndim, x3.ndim)
0 1 2 3
```

### `shape` 속성: 텐서의 모양을 튜플로 저장


```python
>>> print(x0.shape, x1.shape, x2.shape, x3.shape)
() (5,) (3, 5) (2, 5, 3)
```

### `dtype` 속성: 텐서에 포함된 항목의 통일된 자료형

```python
>>> print(x0.dtype, x1.dtype, x2.dtype, x3.dtype)
float64 int64 int64 float64
```

### 3.1.3. 넘파이 어레이 실전 예제

### 2D 어레이 데이터셋

- 예제: 캘리포니아 구역별 인구조사 데이터셋
- 20,640개의 구역별 데이터 포함. 따라서 `(20640, 10)` 모양의 2D 어레이로 표현 가능.

<img src="https://raw.githubusercontent.com/codingalzi/handson-ml3/master/jupyter-book/imgs/ch02/housing-data.png" style="width:600px;">

### 3D 어레이 데이터셋

- 예제: 흑백 손글씨 사진으로 구성된 MNIST 데이터셋

- 샘플: `28x28` 크기의 (흑백) 손글씨 사진.
    `(28, 28)` 모양의 2D 텐서로 표현 가능.

- MNIST 훈련 데이터셋: 총 6만개의 (흑백) 손글씨 사진으로 구성됨.
    `(60000, 28, 28)` 모양의 3D 어레이로 표현 가능.

### 4D 텐서 예제

- 컬러 사진으로 구성된 데이터셋: `(샘플 수, 높이, 너비, 채널 수)` 또는 `(샘플 수, 채널 수, 높이, 너비)`
    모양의 4D 텐서로 표현

<div align="center"><img src="https://drek4537l1klr.cloudfront.net/chollet2/v-7/Figures/ch02-image_data.png" style="width:350px;"></div>

## 3.2. 텐서플로우의 텐서

### `tf.Tensor` 자료형

- 입출력 데이터 등 변하지 않는 값을 다룰 때 사용.

- 불변 자료형

### `tf.Variable` 자료형

- 모델의 가중치, 편향 등 항목의 업데이트가 필요할 때 사용되는 텐서.

- 가변 자료형

### 3.2.1. 불변 텐서

- 아래 방식으로 직접 정의 가능

```python
>>> x = tf.constant([[1., 2.], [3., 4.]])
>>> print(x)
```

```python
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
```

- 넘파이 어레이의 경우와 유사한 방식으로 다양한 불변 텐서 생성 가능

```python
>>> x = tf.ones(shape=(2, 1))
>>> print(x)
```

```python
tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
```

```python
>>> x = tf.zeros(shape=(2, 1))
>>> print(x)
```

```python
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)
```

```python
>>> x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
>>> print(x)
```

```python
tf.Tensor(
[[ 1.3731117 ]
 [ 0.5951849 ]
 [-0.28321794]], shape=(3, 1), dtype=float32)
```

```python
>>> x = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.)
>>> print(x)
```

```python
tf.Tensor(
[[0.06819296]
 [0.9727112 ]
 [0.16666853]], shape=(3, 1), dtype=float32)
```

### 불변 텐서의 수정 불가능성

- 한 번 생성된 불변 텐서는 수정이 불가능.

```python
>>> x[0, 0] = 1.0
```

```python
TypeError                                 Traceback (most recent call last)
Cell In[10], line 1
----> 1 x[0, 0] = 1.0

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment
```

- 반면에 넘파이 어레이는 수정 가능

```python
>>> y = np.ones(shape=(2, 2))
>>> y[0, 0] = 0.0
>>> print(y)
```

```python
[[0. 1.]
 [1. 1.]]
```

### 3.2.2. 가변 텐서

- `tf.Variaible` 객체는 항목을 수정할 수 있는 가변 텐서임.

```python
>>> v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
>>> print(v)
```

```python
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.84899724],
       [-1.3992549 ],
       [-0.22706768]], dtype=float32)>
```

### 가변 텐서 대체

- `assign` 메서드 활용

```python
>>> v.assign(tf.ones((3, 1)))
```

```python
<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>
```

- 단, 대체하는 텐서의 모양(shape)이 기존 텐서의 모양과 동일해야 함.

```python
>>> v.assign(tf.ones((3, 2)))
```

```python
ValueError         Traceback (most recent call last)

...(중략)

ValueError: Cannot assign value to variable ...(이하 생략)
```

### 가변 텐서 항목 수정

- `assign` 메서드 활용

```python
>>> v[0, 0].assign(3.)
```

```python
<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>
```

### `assign_add()`와 `assign_sub()`

- `assign_sub()` 메서드: `-=` 연산자와 유사
- `assign_add()` 메서드는 `+=` 연산자와 유가
- 경사하강법 적용과정에서 가중치와 편향 텐서를 업데이트할 때 사용됨.

```python
>>> v.assign_sub(tf.ones((3, 1)))
```

```python
<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[2.],
       [0.],
       [0.]], dtype=float32)>
```

### 3.2.3. 차원과 모양

### 스칼라: 0차원 텐서

```python
>>> d0_tensor = tf.constant(4)
>>> print(d0_tensor)
tf.Tensor(4, shape=(), dtype=int32)

>>> print("차원:", d0_tensor.ndim)
차원: 0

>>> print("모양:", d0_tensor.shape)
모양: ()

>>> print("항목 자료형:", d0_tensor.dtype)
항목 자료형: <dtype: 'int32'>
```

### 벡터: 1차원 텐서

```python
>>> d1_tensor = tf.constant([2.0, 3.0, 4.0])
>>> print(d1_tensor)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)

>>> print("차원:", d1_tensor.ndim)
차원: 1

>>> print("모양:", d1_tensor.shape)
print("모양:", d1_tensor.shape)

>>> print("항목 자료형:", d1_tensor.dtype)
print("항목 자료형:", d1_tensor.dtype)
```

### 행렬: 2차원 텐서

```python
>>> d2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)

>>> print(d2_tensor)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=int16)

>>> print("차원:", d2_tensor.ndim)
차원: 2

>>> print("모양:", d2_tensor.shape)
모양: (3, 2)

>>> print("항목 자료형:", d2_tensor.dtype)
항목 자료형: <dtype: 'float16'>
```

- `dtype=tf.float16` 활용에 주의할 것.

```python
>>> d2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]])

>>> print(d2_tensor)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=int32)
```

### 스칼라, 벡터, 행렬 시각화

<table>
<tr>
  <th>스칼라, 모양: <code>[]</code> </th>
  <th>벡터, 모양: <code>[3]</code> </th>
  <th>행렬, 모양: <code>[3, 2]</code> </th>
</tr>
<tr>
  <td>    <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/scalar.png" alt="A scalar, the number 4"> </td>
  <td>    <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/vector.png" alt="The line with 3 sections, each one containing a number.">   </td>
  <td>    <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/matrix.png" alt="A 3x2 grid, with each cell containing a number.">   </td>
</tr>
</table>

### 3차원 텐서

```python
>>> d3_tensor = tf.constant([[[0, 1, 2, 3, 4],
                              [5, 6, 7, 8, 9]],
                             [[10, 11, 12, 13, 14],
                              [15, 16, 17, 18, 19]],
                             [[20, 21, 22, 23, 24],
                              [25, 26, 27, 28, 29]]
                            ])
```

```python
>>> print(d3_tensor)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)

>>> print("차원:", d3_tensor.ndim)
차원: 3

>>> print("모양:", d3_tensor.shape)
모양: (3, 2, 5)

>>> print("항목 자료형:", d3_tensor.dtype)
항목 자료형: <dtype: 'int32'>
```

### 3차원 텐서 이해 방식

<table>
<tr>
</tr>
<tr>
  <td>    <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/3-axis_numpy.png">   </td>
  <td>    <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/3-axis_front.png">   </td>
  <td>    <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/3-axis_block.png">   </td>
</tr>
</table>

### 4차원 텐서

```python
>>> d4_tensor = tf.zeros([3, 2, 4, 5])

>>> print("차원:", d4_tensor.ndim)
차원: 4

>>> print("모양:", d4_tensor.shape)
모양: (3, 2, 4, 5)

>>> print("항목 자료형:", d4_tensor.dtype)
항목 자료형: <dtype: 'flot32'>
```

### 4차원 텐서의 축과 모양

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/shape.png" alt="A tensor shape is like a vector.">     </td>
<td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/4-axis_block.png" alt="A 4-axis tensor">   </td>
  </tr>
</table>

### 축의 순서 이해

<table>
<tr>
    <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/shape2.png" alt="Keep track of what each axis is. A 4-axis tensor might be: Batch, Width, Height, Features">   </td>
</tr>
</table>

### 3.2.4. 넘파이 어레이로의 변환

```python
>>> np.array(d2_tensor)
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)
```

또는

```python
>>> d2_tensor.numpy()
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)
```

## 텐서 연산

### 항목별 덧셈

```python
>>> a = tf.constant([[1, 2],
...                  [3, 4]])

>>> b = tf.ones([2,2])

>>> tf.add(a, b)
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>
```

또는

```python
>>> a + b
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>
```

### 항목별 곱셈

```python
>>> a = tf.constant([[1, 2],
...                  [3, 4]])

>>> b = tf.ones([2,2])

>>> tf.multiply(a, b)
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>
```

또는

```python
>>> a * b
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>
```

### 행렬 연산

```python
>>> a = tf.constant([[1, 2],
...                  [3, 4]])

>>> b = tf.ones([2,2])

>>> tf.matmul(a, b)
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]])>
```

또는

```python
>>> a @ b
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]])>
```

### 최대 항목 찾기

```python
>>> c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

>>> tf.reduce_max(c)
<tf.Tensor: shape=(), dtype=float32, numpy=10.0>
```

### 최대 항목의 인덱스 확인

```python
>>> c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

>>> tf.math.argmax(c)
<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0], dtype=int64)>
```

### `softmax()` 함수

```python
>>> c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

>>> tf.nn.softmax(c)
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>
```

### 텐서 자동 변환

연산 결과는 기본적으로 `tf.Tensor`로 반환된다.

```python
>>> tf.convert_to_tensor([1,2,3])
<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

>>> tf.reduce_max([1, 2, 3])
<tf.Tensor: shape=(), dtype=int32, numpy=3>

>>> tf.math.argmax([1, 2, 3])
<tf.Tensor: shape=(), dtype=int64, numpy=2>

>>> tf.nn.softmax(np.array([1.0, 12.0, 33.0]))
<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.26641655e-14, 7.58256042e-10, 9.99999999e-01])>
```

## 텐서의 모양, 랭크, 축, 크기

넘파이 어레이의 경우와 동일하다.

- **모양**: 텐서에 사용된 각각의 축에 사용된 항목의 개수로 구성된 벡터
- **랭크** 또는 **차원**: 텐서에 사용된 축의 개수
    - 스칼라의 랭크는 0,
    - 벡터의 랭크는 1,
    - 행렬의 랭크는 2.
- **축**: 텐서 구성에 사용된 축
- **크기**: 텐서에 포함된 항목의 개수

### 랭크-4 텐서 이해

```python
rank_4_tensor = tf.zeros([3, 2, 4, 5])
```

<table>
<tr>
    <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/shape.png" alt="A tensor shape is like a vector.">     </td>
    <td><img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/shape2.png"></td>
    <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/4-axis_block.png" alt="A 4-axis tensor">   </td>
  </tr>
</table>

```python
>>> rank_4_tensor.dtype
tf.float32

>>> rank_4_tensor.ndim
4

>>> rank_4_tensor.shape
TensorShape([3, 2, 4, 5])

>>> rank_4_tensor.shape[0]
3

>>> rank_4_tensor.shape[-1]
5

>>> tf.size(rank_4_tensor)
<tf.Tensor: shape=(), dtype=int32, numpy=120>

>>> tf.rank(rank_4_tensor)
<tf.Tensor: shape=(), dtype=int32, numpy=4>

>>> tf.shape(rank_4_tensor)
<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 4, 5])>
```

## 인덱싱/슬라이싱

넘파이 어레이의 경우와 동일하다.

```python
>>> rank_3_tensor[:, :, 4]
<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  9],
       [14, 19],
       [24, 29]])>
```

<table>
<tr>
    <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/index1.png" style="width:350px;">   </td>
      <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/index2.png" style="width:160px;">   </td>
</tr>
</table>

## 모양 변환

### 항목 저장 순서

```python
>>> rank_3_tensor
```

<div align="center"><img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/index1.png" style="width:400px;"></div>


```python
>>> tf.reshape(rank_3_tensor, [-1])
<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])>
```

### 축의 순서를 고려하는 좋은 모양 변환

전체 항목의 수를 유지하면서 축별 길이를 고려하는 모양 변환이 유용하다.

```python
>>> tf.reshape(rank_3_tensor, [3*2, 5])
<tf.Tensor: shape=(6, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])>
```

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-before.png" style="width:350px;">   </td>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-good2.png" style="width:270px;">   </td>
</tr>
</table>


-1은 나머지 항목수를 자동으로 정하라는 의미이다.

```python
>>> tf.reshape(rank_3_tensor, [3, -1])
<tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])>
```

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-before.png" style="width:350px;">   </td>
  <td>   <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-good1.png" style="width:450px;">   </td>
</tr>
</table>


### 축의 순서를 고려하지 않는 나쁜 모양 변환

전체 항목의 수 또는 축별 크기를 고려하지 않는 모양 변환은 의미가 없다.

```python
>>> tf.reshape(rank_3_tensor, [2, 3, 5])

>>> tf.reshape(rank_3_tensor, [5, 6])

>>> try:
...   tf.reshape(rank_3_tensor, [7, -1])
... except Exception as e:
...   print(f"{type(e).__name__}: {e}")
```

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-bad.png" alt="You can't reorder axes, use tf.transpose for that">   </td>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-bad4.png" alt="Anything that mixes the slices of data together is probably wrong.">   </td>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/reshape-bad2.png" alt="The new shape must fit exactly.">   </td>
</tr>
</table>

## 텐서 항목의 자료형(`dtype`) 변환

생성된 텐서 항목의 자료형을 임의로 지정할 수 있다.

```python
>>> the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
>>> the_f64_tensor
<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.2, 3.3, 4.4])>

>>> the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
>>> the_f16_tensor
<tf.Tensor: shape=(3,), dtype=float16, numpy=array([2.2, 3.3, 4.4], dtype=float16)>

>>> the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
>>> the_u8_tensor
<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([2, 3, 4], dtype=uint8)>
```

## 브로드캐스팅

넘파이 어레이의 경우와 동일하게 작동한다.

```python
>>> x = tf.constant([1, 2, 3])
>>> y = tf.constant(2)
>>> z = tf.constant([2, 2, 2])

>>> tf.multiply(x, 2)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)

>>> x * y
tf.Tensor([2 4 6], shape=(3,), dtype=int32)

>>> x * z
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
```

```python
>>> x = tf.reshape(x,[3,1])
>>> y = tf.range(1, 5)

>>> x * y
<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])>
```

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/broadcasting.png" style="width:350px;">   </td>
</tr>
</table>


## 다양한 종류의 텐서

### 비정형 텐서

벡터의 길이가 일정하지 않은 축이 사용되는 텐서를 가리킨다.

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/ragged.png" style="width:200px;">   </td>
</tr>
</table>

```python
>>> ragged_list = [
...     [0, 1, 2, 3],
...     [4, 5],
...     [6, 7, 8],
...     [9]]

>>> ragged_tensor = tf.ragged.constant(ragged_list)
>>> ragged_tensor
<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>

>>> ragged_tensor.shape
(4, None)
```

### 희소 텐서

텐서의 크기가 매우 큰 반면에 0이 아닌 항목의 개수가 상대적으로 적을 때 사용한다.

<table>
<tr>
  <td> <img src="https://raw.githubusercontent.com/tensorflow/docs/master/site/en/guide/images/tensor/sparse.png" style="width:200px;">   </td>
</tr>
</table>

```python
>>> sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
...                                        values=[1, 2],
...                                        dense_shape=[3, 4])

>>> sparse_tensor
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
```

### 밀집 텐서 대 희소 텐서

필요에 따라 자동으로 변환되지만 지정할 수도 있다.

```python
>>> dense_tensor = tf.sparse.to_dense(sparse_tensor)

>>> dense_tensor
<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]])>


>>> tf.sparse.from_dense(dense_tensor)
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
```