# 2. 신경망 기본 구성 요소

__감사말__

프랑소와 숄레의 [Deep Learning with Python, Second Edition](https://www.manning.com/books/deep-learning-with-python-second-edition?a_aid=keras&a_bid=76564dff) 2장에 사용된 코드에 대한 설명을 담고 있으며 텐서플로우 2.6 버전 이상에서 작성되었습니다. 소스코드를 공개한 저자에게 감사드립니다.

__구글 코랩 설정__

'런타임 -> 런타임 유형 변경' 메뉴에서 GPU를 지정한다.
TensorFlow 버전을 확인하려면 아래 명령문을 실행한다.

In [1]:
import tensorflow as tf
tf.__version__

'2.12.0'

TensorFlow가 GPU를 사용하는지 여부를 확인하려면 아래 명령문을 실행한다.
아래와 같은 결과가 나오면 GPU가 제대로 지원됨을 의미한다.

```
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

In [2]:
tf.config.list_physical_devices('GPU')

[]

**참고**

아래 코드에 대한 자세한 설명은
[신경망 구성 요소](https://codingalzi.github.io/dlp2/building_blocks_of_NN.html)를
참고한다.

## 신경망 모델 기초 훈련법

**케라스로 MNIST 데이터셋 불러오기**

In [3]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

훈련셋 정보

In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
len(train_labels)

60000

In [6]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

테스트셋 정보

In [7]:
test_images.shape

(10000, 28, 28)

In [8]:
len(test_labels)

10000

In [9]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

**신경망 모델의 구조 지정**

In [10]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

**신경망 모델 컴파일**

In [11]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

**이미지 데이터 전처리**

In [12]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255   # 0과 1사이의 값
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255     # 0과 1사이의 값

**모델 훈련**

In [13]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 8s 12ms/step - loss: 0.2648 - accuracy: 0.9233
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 0.1083 - accuracy: 0.9690
Epoch 3/5
469/469 [==============================] - 5s 11ms/step - loss: 0.0712 - accuracy: 0.9789
Epoch 4/5
469/469 [==============================] - 5s 11ms/step - loss: 0.0518 - accuracy: 0.9844
Epoch 5/5
469/469 [==============================] - 5s 12ms/step - loss: 0.0385 - accuracy: 0.9883


## 훈련된 모델 활용과 평가

**모델 활용: 예측하기**

In [14]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)

1/1 [==============================] - 0s 93ms/step


0번 이미지에 대한 예측값

In [15]:
predictions[0]

array([9.8907456e-08, 2.3016495e-08, 5.5109708e-06, 2.6674548e-05,
       1.9311407e-10, 8.1893342e-07, 4.3698378e-12, 9.9995857e-01,
       1.4703568e-06, 6.8140566e-06], dtype=float32)

가장 높은 확률값을 갖는 인덱스는 7.

In [16]:
predictions[0].argmax()

7

0번 이미지가 가리키는 숫자가 7일 확률이 99.98% 정도.

In [17]:
predictions[0][7]

0.9999586

실제로 첫째 이미지의 레이블이 7임.

In [18]:
test_labels[0]

7

**모델 성능 테스트**

In [19]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 [==============================] - 1s 3ms/step - loss: 0.0689 - accuracy: 0.9782
test_acc: 0.9782000184059143
